import 'dart:ui';

import 'package:dusty_dust/model/status_model.dart';
import 'package:flutter/material.dart';

const statusLevels = [
  StatusModel(
      level: 0,
      lable: '최고',
      primaryColor: Color(0XFF2196F3),
      darkColor: Color(0XFF0069C0),
      lightColor: Color(0XFF6EC6FF),
      fontColor: Colors.black,
      iamgePath:'assets/img/best.png',
      comment: '우와! 100년에 한번 오는날!!',
      minPM10: 0,
      minPM25: 0,
      minO3: 0,
      minNO2: 0,
      minCO: 0,
      minSO2: 0,
  ),
  StatusModel(
    level: 1,
    lable: '좋음',
    primaryColor: Color(0XFF03a9f4),
    darkColor: Color(0XFF007ac1),
    lightColor: Color(0XFF67daff),
    fontColor: Colors.black,
    iamgePath:'assets/img/good.png',
    comment: '공기가 좋아요 외부활동 해도 되는날!!',
    minPM10: 16,
    minPM25: 9,
    minO3: 0.02,
    minNO2: 0.02,
    minCO: 1,
    minSO2: 0.01,
  ),
  StatusModel(
    level: 2,
    lable: '양호',
    primaryColor: Color(0XFF00BCD4),
    darkColor: Color(0XFF008ba3),
    lightColor: Color(0XFF62efff),
    fontColor: Colors.black,
    iamgePath:'assets/img/ok.png',
    comment: '공기가 좋은 날이예요!!',
    minPM10: 31,
    minPM25: 16,
    minO3: 0.03,
    minNO2: 0.03,
    minCO: 2,
    minSO2: 0.02,
  ),
  StatusModel(
    level: 3,
    lable: '보통',
    primaryColor: Color(0XFF009688),
    darkColor: Color(0XFF00675b),
    lightColor: Color(0XFF52c7b8),
    fontColor: Colors.black,
    iamgePath:'assets/img/mediocre.png',
    comment: '나쁘지 않네요!!',
    minPM10: 41,
    minPM25: 21,
    minO3: 0.06,
    minNO2: 0.05,
    minCO: 5.5,
    minSO2: 0.04,
  ),
  StatusModel(
    level: 4,
    lable: '나쁨',
    primaryColor: Color(0XFFffc107),
    darkColor: Color(0XFFc79100),
    lightColor: Color(0XFFfff350),
    fontColor: Colors.black,
    iamgePath:'assets/img/bad.png',
    comment: '공기가 안좋아요!!',
    minPM10: 51,
    minPM25: 26,
    minO3: 0.09,
    minNO2: 0.06,
    minCO: 9,
    minSO2: 0.05,
  ),
  StatusModel(
    level: 5,
    lable: '상당히 나쁨',
    primaryColor: Color(0XFFff9800),
    darkColor: Color(0XFFc66900),
    lightColor: Color(0XFFffc947),
    fontColor: Colors.black,
    iamgePath:'assets/img/very_bad.png',
    comment: '공기가 나빠요 외부횔동을 자제해 주세요',
    minPM10: 76,
    minPM25: 38,
    minO3: 0.12,
    minNO2: 0.13,
    minCO: 12,
    minSO2: 0.1,
  ),
  StatusModel(
    level: 6,
    lable: '매우나쁨',
    primaryColor: Color(0XFFf44336),
    darkColor: Color(0XFFba000d),
    lightColor: Color(0XFFff7961),
    fontColor: Colors.black,
    iamgePath:'assets/img/worse.png',
    comment: '매우 안졸아요!나가지 마세요!',
    minPM10: 101,
    minPM25: 51,
    minO3: 0.15,
    minNO2: 0.2,
    minCO: 15,
    minSO2: 0.15,
  ),
  StatusModel(
    level: 7,
    lable: '최악',
    primaryColor: Color(0XFF212121),
    darkColor: Color(0XFF000000),
    lightColor: Color(0XFFff7961),
    fontColor: Colors.black,
    iamgePath:'assets/img/worst.png',
    comment: '약대급 최악의 날!나가지 마세요!',
    minPM10: 151,
    minPM25: 76,
    minO3: 0.38,
    minNO2: 1.1,
    minCO: 32,
    minSO2: 0.16,
  ),
];